apiVersion: v2
name: "cray-hms-firmware-action"
version: 3.0.10
description: "Kubernetes resources for cray-hms-firmware-action"
home: "https://github.com/Cray-HPE/hms-firmware-action-charts"
sources:
  - "https://github.com/Cray-HPE/hms-firmware-action"
dependencies:
  - name: cray-service
    version: "~10.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-etcd-base
    version: "~1.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "1.33.1"
annotations:
  artifacthub.io/license: "MIT"
