name: Build and Publish Helm charts
on: 
  push: {}
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: {}
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-chart-workflows/.github/workflows/build_and_release_charts.yaml@v2
    with:
      artifactory-component: cray-hms-firmware-action
      target-branch: main
    secrets: inherit
